source 'https://rubygems.org'

gem 'sequel'
gem 'htmlbeautifier'
gem 'rake', '~> 12.0'
gem 'mysql2', '~> 0.4.6'
gem 'colorize', '~> 0.8.1'
gem 'watir', '~> 6.2', '>= 6.2.1'
gem 'chromedriver-helper', '~> 1.1'
gem 'in_threads', '~> 1.3', '>= 1.3.1'
# gem 'page-object', '~> 2.1', '>= 2.1.1'
gem 'spreadsheet', '~> 1.1', '>= 1.1.4'
gem 'page-object', github: 'cheezy/page-object'
gem 'mechanize', github: 'sparklemotion/mechanize'
# gem 'httparty'
# gem 'watir', github: 'brianpurgert2/watir'