source 'https://rubygems.org'

# gem 'sinatra'
# gem 'erubi'
# gem 'roda'
# gem 'forme'
# gem 'rubyzip'
gem 'axlsx', github: 'randym/axlsx'
gem 'in_threads', '~> 1.4'
gem 'mysql2', '~> 0.4.6'
gem 'sequel', '~> 4.47'
gem 'htmlbeautifier'
gem 'rake', '~> 12.0'
# gem install mysql2 --with-mysql-dir[=C:\Program Files\MySQL\MySQL Connector.C 6.1]
# gem install mysql2 --with-mysql-dir=C:\Program Files\MySQL\MySQL Connector.C 6.1
gem 'colorize', '~> 0.8.1'
gem 'rest-client', '~> 1.8'
gem 'chromedriver-helper', '~> 1.1'
gem 'roo', '~> 2.7', '>= 2.7.1'
gem 'roo-xls'
# gem 'spreadsheet', '~> 1.1', '>= 1.1.4'
gem 'page-object', github: 'cheezy/page-object'
gem 'mechanize', github: 'sparklemotion/mechanize'
# gem 'httparty'
# gem 'watir', github: 'watir', :branch => '6_3_0'
gem 'watir', '~> 6.3'

