gsa_data_querys:
    - _a
    - _cview
    - _q
    - app
    - bpaNumber
    - cat
    - contract
    - contractNumber
    - contractorName
    - db
    - dir
    - duns
    - executeQuery
    - filter
    - flag
    - fromPage
    - gsin
    - id
    - itemNumber
    - keyName
    - listFor
    - mapName
    - mfrName
    - mode
    - nc
    - oid
    - p
    - path
    - q
    - s
    - scheduleNumber
    - scheduleNumber
    - searchType
    - sin
    - sortBy
    - sortOrder
    - source
    - specialItemNumber
    - src
    - subcategoryCode
    - tab
    - type
    - uom
    - utm_campaign
    - utm_content
    - utm_medium
    - utm_source
    - view